version: "3.9"

services:
  webservergo:
    build: .
    ports:
      - 3000:8080
  nginx:
    image: nginx
    volumes:
      - ./nginx:/usr/share/nginx/html
    ports:
      - 8080:80
  redis:
    image: redis
    expose: 
      - 6379